wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.7
    cli_version: 0.17.3
    framework: lightning
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1719408363
    t:
      1:
      - 1
      - 9
      - 41
      - 55
      - 103
      2:
      - 1
      - 9
      - 41
      - 55
      - 103
      3:
      - 13
      - 23
      4: 3.11.7
      5: 0.17.3
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
